apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controlplane
  namespace: argocd
spec:
  description:  Controlplane Project
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - '*'