kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-admin
  namespace: vcluster-project-x
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: sso:you-group@xy.com
    apiGroup: rbac.authorization.k8s.io
