apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-project-z
spec:
  destination:
    name: ""
    namespace: vcluster-project-z
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: https://github.com/la-cc/webinar-gitops-vcluster-kubernetes-platform.git
      path: vcluster/project-z
      targetRevision: main
    - repoURL: https://github.com/la-cc/webinar-gitops-vcluster-kubernetes-platform.git
      targetRevision: main
      ref: valuesRepo
    - repoURL: https://github.com/la-cc/webinar-gitops-vcluster-kubernetes-platform.git
      targetRevision: main
      path: "./kubernetes-service-catalog/optimization/vcluster"
      helm:
        releaseName: "vcluster"
        valueFiles:
          - "values.yaml"
          - "$valuesRepo/vcluster/project-z/helm/values.yaml"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false